### ISSUE TITLE
Version 2 Roadmap

### ISSUE THREAD

**Issue by linhub15** [linhub15/yeg-property-assessment#4]
# Version 2 Roadmap
Version 2 is on the road map this year. Bug fixes and new features coming.
Changes will be in `main` branch

## New Features
- [x] rebrand as `OpenProperty`
- [x] display historical assessed value for a property (I'm thinking a line graph)

## Bugs
- [x] fix: data set URL
  * `Property` https://data.edmonton.ca/City-Administration/Property-Information-Current-Calendar-Year-/dkk9-cj3x
  * `History` https://data.edmonton.ca/City-Administration/Property-Assessment-Data-Historical-/qi6a-xuwt
- [x] fix: google map showing old address when selecting another address

## Tech / Upgrades
- [x] use new Google Maps Angular component library
- [x] host for free on Cloudflare pages
- [x] `ng-soda-client` must handle property queries
- [x] upgrade to latest Angular version https://update.angular.io/
- [x] reduce web traffic when searching `onchange`

## Future 
- [ ] ux: mobile
- [ ] ux: tablet
- [ ] ux: dark theme
- [ ] feat: aggregate with neighborhood data like [Pets](https://data.edmonton.ca/Community-Services/Pet-Licenses-by-Neighbourhood/5squ-mg4w), [Maturity](https://data.edmonton.ca/Geospatial-Boundaries/Mature-Neighbourhoods/gnzw-67i5), crime,
- [ ] feat: add Calgary data
